from typing import Any

class Response:
    content: bytes
    text: str

    def json(self) -> Any: ...

class Client:
    def request(self, method: str, url: str, **kwargs: Any) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...

class AsyncClient:
    def request(self, method: str, url: str, **kwargs: Any) -> Any: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...

def request(method: str, url: str, **kwargs: Any) -> Response: ...
def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, **kwargs: Any) -> Response: ...
def put(url: str, **kwargs: Any) -> Response: ...
def patch(url: str, **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...
def __getattr__(name: str) -> Any: ...
