from typing import Any

from werkzeug.sansio.request import Request as SansIORequest

class Request(SansIORequest):
    @property
    def data(self) -> Any: ...
    @property
    def files(self) -> Any: ...
    @property
    def form(self) -> Any: ...
    @property
    def json(self) -> Any: ...
    @property
    def values(self) -> Any: ...
    @property
    def view_args(self) -> Any: ...
    def get_data(self, cache: bool = ..., as_text: bool = ..., parse_form_data: bool = ...) -> Any: ...
    def get_json(self, force: bool = ..., silent: bool = ..., cache: bool = ...) -> Any: ...
