"""Channel-neutral Human Input management contracts."""

from .commands import (
    DeleteChannelCommand,
    GetChannelCommand,
    SaveEmailChannelCommand,
    SaveIMChannelCommand,
    TestEmailChannelCommand,
    TestIMChannelCommand,
)
from .contracts import (
    ChannelCapability,
    ChannelCollectionResult,
    ChannelFailure,
    ChannelFailureCategory,
    ChannelKind,
    ChannelOperation,
    ChannelOperationResult,
    ChannelProvider,
    ChannelRef,
    ChannelScope,
    ChannelScopeKind,
    ChannelStatus,
    ChannelTestResult,
    ChannelView,
    HumanInputChannelManagementContext,
    IMChannelSummary,
    IMChannelTestSummary,
    ResendChannelSummary,
    ResendChannelTestSummary,
)
from .handlers import ChannelHandler, ChannelHandlerRegistry, DuplicateChannelHandlerError
from .im_candidates import (
    DingTalkIMCandidate,
    FeishuIMCandidate,
    IMCandidate,
    NewSecret,
    SlackIMCandidate,
)

__all__ = [
    "ChannelCapability",
    "ChannelCollectionResult",
    "ChannelFailure",
    "ChannelFailureCategory",
    "ChannelHandler",
    "ChannelHandlerRegistry",
    "ChannelKind",
    "ChannelOperation",
    "ChannelOperationResult",
    "ChannelProvider",
    "ChannelRef",
    "ChannelScope",
    "ChannelScopeKind",
    "ChannelStatus",
    "ChannelTestResult",
    "ChannelView",
    "DeleteChannelCommand",
    "DingTalkIMCandidate",
    "DuplicateChannelHandlerError",
    "FeishuIMCandidate",
    "GetChannelCommand",
    "HumanInputChannelManagementContext",
    "IMCandidate",
    "IMChannelSummary",
    "IMChannelTestSummary",
    "NewSecret",
    "ResendChannelSummary",
    "ResendChannelTestSummary",
    "SaveEmailChannelCommand",
    "SaveIMChannelCommand",
    "SlackIMCandidate",
    "TestEmailChannelCommand",
    "TestIMChannelCommand",
]
