"""added billing interval to tenant plan

Revision ID: 589e4fa4ee00
Revises: c438db259b3e
Create Date: 2024-07-31 12:18:49.572514

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589e4fa4ee00'
down_revision = 'c438db259b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval', sa.Enum('MONTHLY', 'YEARLY', name='planinterval'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_plans', schema=None) as batch_op:
        batch_op.drop_column('interval')

    # ### end Alembic commands ###
