coverage:
  status:
    project:
      default:
        target: auto

flags:
  web:
    paths:
      - "web/"
    carryforward: true

  dify-ui:
    paths:
      - "packages/dify-ui/"
    carryforward: true

  api:
    paths:
      - "api/"
    carryforward: true
