"""Public contracts for deployment-selected runtime backends."""

from .errors import (
    BindingAcquireError,
    BindingCreateError,
    BindingDestroyError,
    BindingLostError,
    HomeSnapshotCreateError,
    HomeSnapshotNotFoundError,
    RuntimeBackendError,
    SharedWorkspaceUnsupportedError,
    WorkspaceFileTooLargeError,
    WorkspacePathError,
    WorkspacePreservationUnsupportedError,
    WorkspaceUnavailableError,
)
from .protocols import (
    ExecutionBindingAllocation,
    ExecutionBindingBackend,
    ExecutionBindingCreateSpec,
    ExecutionBindingDestroySpec,
    FileSystem,
    HomeSnapshotBackend,
    HomeSnapshotCreateSpec,
    RuntimeBackendProfile,
    RuntimeLayout,
    RuntimeLease,
    WorkspaceFileContent,
    WorkspaceFileEntry,
    WorkspaceListResult,
    WorkspaceReadResult,
)

__all__ = [
    "BindingAcquireError",
    "BindingCreateError",
    "BindingDestroyError",
    "BindingLostError",
    "ExecutionBindingAllocation",
    "ExecutionBindingBackend",
    "ExecutionBindingCreateSpec",
    "ExecutionBindingDestroySpec",
    "FileSystem",
    "HomeSnapshotBackend",
    "HomeSnapshotCreateError",
    "HomeSnapshotCreateSpec",
    "HomeSnapshotNotFoundError",
    "RuntimeBackendError",
    "RuntimeBackendProfile",
    "RuntimeLayout",
    "RuntimeLease",
    "SharedWorkspaceUnsupportedError",
    "WorkspaceFileContent",
    "WorkspaceFileEntry",
    "WorkspaceFileTooLargeError",
    "WorkspaceListResult",
    "WorkspacePathError",
    "WorkspacePreservationUnsupportedError",
    "WorkspaceReadResult",
    "WorkspaceUnavailableError",
]
