"""Pure recipient resolution for Human Input v2 approval plans.

The package accepts immutable workflow recipient specifications and current
Contact/endpoint capability snapshots. It returns immutable domain decisions;
transport DTOs, provider clients, database sessions, and ORM records remain at
their respective adapters.
"""

from .delivery import (
    ConsoleEndpointConfiguration,
    DeliveryAttempt,
    DeliveryEndpoint,
    DeliveryEndpointConfiguration,
    EmailEndpointConfiguration,
    EmailProviderConfiguration,
    EndpointAccessCapability,
    IMEndpointConfiguration,
    UploadCapability,
    UploadCapabilityRef,
    UploadFileAssociation,
    WebEndpointConfiguration,
)
from .form import (
    FormCreation,
    FormInactiveReason,
    FormSnapshotIdentifierFactory,
    FormState,
    FrozenFormAction,
    FrozenFormDefinition,
    HumanInputForm,
    InactiveFormState,
    InvalidApproverGrantError,
    InvalidSelectedActionError,
    SubmissionTransitionDecision,
    WaitingFormState,
)
from .frozen_values import FrozenJSONArray, FrozenJSONObject, JSONPrimitive
from .grants import ApproverGrant, ApproverGrantRef, DeliveryEndpointRef, FormRef
from .ports import FormDefinitionProjection, FormDeliveryProjection, FormRepository
from .recipient_resolution import (
    ApprovalSubject,
    CanonicalSubjectKey,
    ConsoleEndpointPlan,
    ContactApprovalSubject,
    ContactInitiatorSnapshot,
    DebugRecipientReplacement,
    DeliveryCapabilitySnapshot,
    DeliveryEndpointPlan,
    EmailAddressApprovalSubject,
    EmailEndpointPlan,
    EndUserApprovalSubject,
    EndUserInitiatorSnapshot,
    IMEndpointPlan,
    MatchedRecipientSource,
    RecipientRejectionReason,
    RecipientResolutionFailureReason,
    RecipientResolver,
    RecipientSourceKind,
    RejectedRecipient,
    ResolvedApprovalPlan,
    ResolvedApprover,
    SubjectSnapshot,
    WebEndpointPlan,
)
from .recipient_specifications import (
    ContactRecipientSpecification,
    CurrentInitiatorRecipientSpecification,
    DynamicEmailRecipientSpecification,
    DynamicRecipientValue,
    OneTimeEmailRecipientSpecification,
    RecipientSpecification,
    RecipientSpecificationKind,
    UnsupportedDynamicRecipientValue,
    WorkflowRecipientSpecificationAdapter,
)

__all__ = [
    "ApprovalSubject",
    "ApproverGrant",
    "ApproverGrantRef",
    "CanonicalSubjectKey",
    "ConsoleEndpointConfiguration",
    "ConsoleEndpointPlan",
    "ContactApprovalSubject",
    "ContactInitiatorSnapshot",
    "ContactRecipientSpecification",
    "CurrentInitiatorRecipientSpecification",
    "DebugRecipientReplacement",
    "DeliveryAttempt",
    "DeliveryCapabilitySnapshot",
    "DeliveryEndpoint",
    "DeliveryEndpointConfiguration",
    "DeliveryEndpointPlan",
    "DeliveryEndpointRef",
    "DynamicEmailRecipientSpecification",
    "DynamicRecipientValue",
    "EmailAddressApprovalSubject",
    "EmailEndpointConfiguration",
    "EmailEndpointPlan",
    "EmailProviderConfiguration",
    "EndUserApprovalSubject",
    "EndUserInitiatorSnapshot",
    "EndpointAccessCapability",
    "FormCreation",
    "FormDefinitionProjection",
    "FormDeliveryProjection",
    "FormInactiveReason",
    "FormRef",
    "FormRepository",
    "FormSnapshotIdentifierFactory",
    "FormState",
    "FrozenFormAction",
    "FrozenFormDefinition",
    "FrozenJSONArray",
    "FrozenJSONObject",
    "HumanInputForm",
    "IMEndpointConfiguration",
    "IMEndpointPlan",
    "InactiveFormState",
    "InvalidApproverGrantError",
    "InvalidSelectedActionError",
    "JSONPrimitive",
    "MatchedRecipientSource",
    "OneTimeEmailRecipientSpecification",
    "RecipientRejectionReason",
    "RecipientResolutionFailureReason",
    "RecipientResolver",
    "RecipientSourceKind",
    "RecipientSpecification",
    "RecipientSpecificationKind",
    "RejectedRecipient",
    "ResolvedApprovalPlan",
    "ResolvedApprover",
    "SubjectSnapshot",
    "SubmissionTransitionDecision",
    "UnsupportedDynamicRecipientValue",
    "UploadCapability",
    "UploadCapabilityRef",
    "UploadFileAssociation",
    "WaitingFormState",
    "WebEndpointConfiguration",
    "WebEndpointPlan",
    "WorkflowRecipientSpecificationAdapter",
]
