export { default as VariableIconWithColor } from '../../../../../nodes/_base/components/variable/variable-label/variable-icon-with-color'
export { default as VariableLabelInEditor } from '../../../../../nodes/_base/components/variable/variable-label/variable-label-in-editor'
export { default as VariableLabelInNode } from '../../../../../nodes/_base/components/variable/variable-label/variable-label-in-node'
export { default as VariableLabelInSelect } from '../../../../../nodes/_base/components/variable/variable-label/variable-label-in-select'
export { default as VariableLabelInText } from '../../../../../nodes/_base/components/variable/variable-label/variable-label-in-text'
