import re
from enum import IntEnum, StrEnum, auto
from typing import Any, Literal, Union

from pydantic import BaseModel, Field, field_validator
from pydantic_core import PydanticCustomError

from core.prompt.entities.advanced_prompt_entities import MemoryConfig
from core.tools.entities.tool_entities import ToolSelector
from dify_graph.entities.base_node_data import BaseNodeData
from dify_graph.enums import BuiltinNodeTypes, NodeType
from dify_graph.nodes.human_input.entities import FormInput, HumanInputNodeData, UserAction, WebAppDeliveryMethod
from dify_graph.nodes.human_input.enums import ButtonStyle, FormInputType

_OUTPUT_IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class AgentNodeData(BaseNodeData):
    type: NodeType = BuiltinNodeTypes.AGENT
    agent_strategy_provider_name: str
    agent_strategy_name: str
    agent_strategy_label: str
    memory: MemoryConfig | None = None
    # The version of the tool parameter.
    # If this value is None, it indicates this is a previous version
    # and requires using the legacy parameter parsing rules.
    tool_node_version: str | None = None

    class AgentInput(BaseModel):
        value: Union[list[str], list[ToolSelector], Any]
        type: Literal["mixed", "variable", "constant"]

    agent_parameters: dict[str, AgentInput]


class AgentClarificationField(BaseModel):
    name: str
    type: FormInputType = FormInputType.TEXT_INPUT

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value: str) -> str:
        if not _OUTPUT_IDENTIFIER_PATTERN.match(value):
            raise PydanticCustomError(
                "agent_clarification_field_name",
                "field name must start with a letter or underscore and contain only letters, numbers, or underscores",
            )
        return value


def _default_clarification_actions() -> list[UserAction]:
    return [UserAction(id="submit", title="Submit", button_style=ButtonStyle.PRIMARY)]


class AgentClarificationPayload(BaseModel):
    """Minimal clarification contract emitted by agent strategies to request human input."""

    question: str
    required_fields: list[str | AgentClarificationField] = Field(default_factory=list)
    display_in_ui: bool = False

    @field_validator("question")
    @classmethod
    def _validate_question(cls, value: str) -> str:
        if not value.strip():
            raise PydanticCustomError("agent_clarification_question", "question must not be empty")
        return value

    def normalized_required_fields(self) -> list[AgentClarificationField]:
        normalized: list[AgentClarificationField] = []
        for field in self.required_fields:
            if isinstance(field, AgentClarificationField):
                normalized.append(field)
            else:
                normalized.append(AgentClarificationField(name=field))
        return normalized

    def to_form_inputs(self) -> list[FormInput]:
        return [
            FormInput(type=field.type, output_variable_name=field.name) for field in self.normalized_required_fields()
        ]

    def to_form_content(self) -> str:
        lines = [self.question.strip()]
        for field in self.normalized_required_fields():
            lines.append(f"- `{field.name}`: {{{{#$output.{field.name}#}}}}")
        return "\n\n".join(lines)

    def to_human_input_node_data(self, *, node_title: str) -> HumanInputNodeData:
        delivery_methods = [WebAppDeliveryMethod()] if self.display_in_ui else []
        return HumanInputNodeData(
            title=node_title,
            form_content=self.to_form_content(),
            inputs=self.to_form_inputs(),
            user_actions=_default_clarification_actions(),
            delivery_methods=delivery_methods,
        )


class ParamsAutoGenerated(IntEnum):
    CLOSE = 0
    OPEN = 1


class AgentOldVersionModelFeatures(StrEnum):
    """
    Enum class for old SDK version llm feature.
    """

    TOOL_CALL = "tool-call"
    MULTI_TOOL_CALL = "multi-tool-call"
    AGENT_THOUGHT = "agent-thought"
    VISION = auto()
    STREAM_TOOL_CALL = "stream-tool-call"
    DOCUMENT = auto()
    VIDEO = auto()
    AUDIO = auto()
