#!/usr/bin/env bash

# start templated
INSTALL_PYTHON=$(which python || command -v python)
if [ -z "$INSTALL_PYTHON" ]; then
    echo "Python3 could not be found. Please ensure it is installed and available in your PATH." 1>&2
    exit 1
fi
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your python environment?' 1>&2
    exit 1
fi
