#!/bin/bash

set -x

# python style checks rely on `isort` in path
if ! command -v isort &> /dev/null
then
    echo "'isort' is not available for linting Python codes. Please run 'pip install isort'."
    exit 1
else
    isort  --settings ./.github/linters/.isort.cfg ./
fi
