#!/bin/bash

set -x

# run ruff linter
uv run --directory api --group lint ruff check --fix ./

# run ruff formatter
uv run --directory api --group lint ruff format ./

# run dotenv-linter linter
uv run --project api --group lint dotenv-linter ./api/.env.example ./web/.env.example

# run mypy check
dev/mypy-check
