#!/bin/bash

set -x

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
cd "$SCRIPT_DIR/../api"

uv run \
  granian \
  --interface asgi \
  --host 127.0.0.1 \
  --port "${DIFY_FASTAPI_PORT:-5004}" \
  fastapi_app:app
