// AUTO-GENERATED — DO NOT EDIT
// Source: https://github.com/anthropics/skills
import type { SkillTemplateEntry } from './types'

export const SKILL_TEMPLATES: SkillTemplateEntry[] = [
  {
    id: 'algorithmic-art',
    name: 'algorithmic-art',
    description: 'Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists\' work to avoid copyright violations.',
    fileCount: 3,
    loadContent: () => import('./skills/algorithmic-art').then(m => m.default),
  },
  {
    id: 'brand-guidelines',
    name: 'brand-guidelines',
    description: 'Applies Anthropic\'s official brand colors and typography to any sort of artifact that may benefit from having Anthropic\'s look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.',
    fileCount: 1,
    loadContent: () => import('./skills/brand-guidelines').then(m => m.default),
  },
  {
    id: 'canvas-design',
    name: 'canvas-design',
    description: 'Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists\' work to avoid copyright violations.',
    fileCount: 82,
    loadContent: () => import('./skills/canvas-design').then(m => m.default),
  },
  {
    id: 'doc-coauthoring',
    name: 'doc-coauthoring',
    description: 'Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This workflow helps users efficiently transfer context, refine content through iteration, and verify the doc works for readers. Trigger when user mentions writing docs, creating proposals, drafting specs, or similar documentation tasks.',
    fileCount: 1,
    loadContent: () => import('./skills/doc-coauthoring').then(m => m.default),
  },
  {
    id: 'docx',
    name: 'docx',
    description: 'Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files). Triggers include: any mention of \\"Word doc\\", \\"word document\\", \\".docx\\", or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a \\"report\\", \\"memo\\", \\"letter\\", \\"template\\", or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.',
    fileCount: 60,
    loadContent: () => import('./skills/docx').then(m => m.default),
  },
  {
    id: 'frontend-design',
    name: 'frontend-design',
    description: 'Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, artifacts, posters, or applications (examples include websites, landing pages, dashboards, React components, HTML/CSS layouts, or when styling/beautifying any web UI). Generates creative, polished code and UI design that avoids generic AI aesthetics.',
    fileCount: 1,
    loadContent: () => import('./skills/frontend-design').then(m => m.default),
  },
  {
    id: 'internal-comms',
    name: 'internal-comms',
    description: 'A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal communications (status reports, leadership updates, 3P updates, company newsletters, FAQs, incident reports, project updates, etc.).',
    fileCount: 5,
    loadContent: () => import('./skills/internal-comms').then(m => m.default),
  },
  {
    id: 'mcp-builder',
    name: 'mcp-builder',
    description: 'Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).',
    fileCount: 9,
    loadContent: () => import('./skills/mcp-builder').then(m => m.default),
  },
  {
    id: 'pdf',
    name: 'pdf',
    description: 'Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple PDFs into one, splitting PDFs apart, rotating pages, adding watermarks, creating new PDFs, filling PDF forms, encrypting/decrypting PDFs, extracting images, and OCR on scanned PDFs to make them searchable. If the user mentions a .pdf file or asks to produce one, use this skill.',
    fileCount: 11,
    loadContent: () => import('./skills/pdf').then(m => m.default),
  },
  {
    id: 'pptx',
    name: 'pptx',
    description: 'Use this skill any time a .pptx file is involved in any way — as input, output, or both. This includes: creating slide decks, pitch decks, or presentations; reading, parsing, or extracting text from any .pptx file (even if the extracted content will be used elsewhere, like in an email or summary); editing, modifying, or updating existing presentations; combining or splitting slide files; working with templates, layouts, speaker notes, or comments. Trigger whenever the user mentions \\"deck,\\" \\"slides,\\" \\"presentation,\\" or references a .pptx filename, regardless of what they plan to do with the content afterward. If a .pptx file needs to be opened, created, or touched, use this skill.',
    fileCount: 58,
    loadContent: () => import('./skills/pptx').then(m => m.default),
  },
  {
    id: 'skill-creator',
    name: 'skill-creator',
    description: 'Guide for creating effective skills. This skill should be used when users want to create a new skill (or update an existing skill) that extends Claude\'s capabilities with specialized knowledge, workflows, or tool integrations.',
    fileCount: 6,
    loadContent: () => import('./skills/skill-creator').then(m => m.default),
  },
  {
    id: 'slack-gif-creator',
    name: 'slack-gif-creator',
    description: 'Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request animated GIFs for Slack like "make me a GIF of X doing Y for Slack.',
    fileCount: 6,
    loadContent: () => import('./skills/slack-gif-creator').then(m => m.default),
  },
  {
    id: 'theme-factory',
    name: 'theme-factory',
    description: 'Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact that has been creating, or can generate a new theme on-the-fly.',
    fileCount: 12,
    loadContent: () => import('./skills/theme-factory').then(m => m.default),
  },
  {
    id: 'web-artifacts-builder',
    name: 'web-artifacts-builder',
    description: 'Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state management, routing, or shadcn/ui components - not for simple single-file HTML/JSX artifacts.',
    fileCount: 4,
    loadContent: () => import('./skills/web-artifacts-builder').then(m => m.default),
  },
  {
    id: 'webapp-testing',
    name: 'webapp-testing',
    description: 'Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser logs.',
    fileCount: 5,
    loadContent: () => import('./skills/webapp-testing').then(m => m.default),
  },
  {
    id: 'xlsx',
    name: 'xlsx',
    description: 'Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing .xlsx, .xlsm, .csv, or .tsv file (e.g., adding columns, computing formulas, formatting, charting, cleaning messy data); create a new spreadsheet from scratch or from other data sources; or convert between tabular file formats. Trigger especially when the user references a spreadsheet file by name or path — even casually (like \\"the xlsx in my downloads\\") — and wants something done to it or produced from it. Also trigger for cleaning or restructuring messy tabular data files (malformed rows, misplaced headers, junk data) into proper spreadsheets. The deliverable must be a spreadsheet file. Do NOT trigger when the primary deliverable is a Word document, HTML report, standalone Python script, database pipeline, or Google Sheets API integration, even if tabular data is involved.',
    fileCount: 53,
    loadContent: () => import('./skills/xlsx').then(m => m.default),
  },
]
