import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { commandTree } from '@/commands/tree.generated'
import { resolveSkillDir, runSkillInit } from './run'

describe('resolveSkillDir', () => {
  it('defaults to ./.claude/skills/difyctl under the cwd', () => {
    expect(resolveSkillDir({ cwd: '/work/project' })).toBe('/work/project/.claude/skills/difyctl')
  })

  it('uses the home directory under --user', () => {
    expect(resolveSkillDir({ user: true, home: '/home/dev' })).toBe('/home/dev/.claude/skills/difyctl')
  })

  it('honors an explicit directory verbatim, even alongside --user', () => {
    expect(resolveSkillDir({ dir: './out/here', user: true, cwd: '/work', home: '/home/dev' }))
      .toBe(resolve('./out/here'))
  })
})

describe('runSkillInit', () => {
  let dir: string

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'difyctl-skill-'))
  })

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true })
  })

  it('writes SKILL.md plus the three reference files into the target dir', async () => {
    const result = await runSkillInit({ outDir: dir, version: '9.9.9-test', tree: commandTree })

    expect(result.dir).toBe(dir)
    expect(result.wrote).toEqual([
      join(dir, 'SKILL.md'),
      join(dir, 'reference/account.md'),
      join(dir, 'reference/external.md'),
      join(dir, 'reference/environment.md'),
    ])

    const skill = await readFile(join(dir, 'SKILL.md'), 'utf8')
    expect(skill).toContain('difyctl v9.9.9-test')
    expect(skill).toContain('@generated by `difyctl skill init`')
    await expect(readFile(join(dir, 'reference/account.md'), 'utf8')).resolves.toContain('account-bearer onboarding')
  })
})
