import type { App } from '@/types/app'
import { AccessMode } from '@/models/access-control'
import { AppModeEnum } from '@/types/app'

export const APP_LIST_SEARCH_DEBOUNCE_MS = 500

const mockAppBase = {
  icon_type: 'emoji',
  icon_url: null,
  use_icon_as_answer_icon: false,
  enable_site: true,
  enable_api: true,
  api_rpm: 0,
  api_rph: 0,
  is_demo: false,
  model_config: {} as App['model_config'],
  app_model_config: {} as App['app_model_config'],
  site: {} as App['site'],
  api_base_url: '',
  tags: [],
  access_mode: AccessMode.PUBLIC,
  max_active_requests: null,
  has_draft_trigger: false,
} satisfies Partial<App>

export const MOCK_APP_LIST: App[] = [
  {
    ...mockAppBase,
    id: 'mock-app-content-brief',
    name: 'Content Brief Builder',
    description: 'Drafts campaign briefs, audience notes, and channel-specific launch copy for marketing teams.',
    author_name: 'Joel',
    icon: '📝',
    icon_background: '#EEF4FF',
    mode: AppModeEnum.CHAT,
    created_at: 1778640000,
    updated_at: 1778640000,
  },
  {
    ...mockAppBase,
    id: 'mock-app-sales-research',
    name: 'Sales Research Copilot',
    description: 'Summarizes accounts, finds buying signals, and prepares concise call notes before customer meetings.',
    author_name: 'Evan',
    icon: '🔎',
    icon_background: '#ECFDF3',
    mode: AppModeEnum.AGENT_CHAT,
    created_at: 1778636400,
    updated_at: 1778636400,
  },
  {
    ...mockAppBase,
    id: 'mock-app-contract-review',
    name: 'Contract Review Flow',
    description: 'Checks uploaded agreements for unusual clauses, missing terms, and follow-up questions.',
    author_name: 'Sarah',
    icon: '📄',
    icon_background: '#FDF2FA',
    mode: AppModeEnum.WORKFLOW,
    created_at: 1778632800,
    updated_at: 1778632800,
  },
  {
    ...mockAppBase,
    id: 'mock-app-support-router',
    name: 'Support Ticket Router',
    description: 'Classifies incoming support requests and routes them to the right queue with priority labels.',
    author_name: 'Maya',
    icon: '🎧',
    icon_background: '#E0F2FE',
    mode: AppModeEnum.ADVANCED_CHAT,
    created_at: 1778629200,
    updated_at: 1778629200,
  },
  {
    ...mockAppBase,
    id: 'mock-app-report-summarizer',
    name: 'Report Summarizer',
    description: 'Turns long operational reports into concise executive summaries with highlights and risks.',
    author_name: 'Dify',
    icon: '📊',
    icon_background: '#FFF7ED',
    mode: AppModeEnum.COMPLETION,
    created_at: 1778625600,
    updated_at: 1778625600,
  },
  {
    ...mockAppBase,
    id: 'mock-app-product-feedback',
    name: 'Product Feedback Miner',
    description: 'Clusters customer feedback, extracts recurring requests, and drafts product insight digests.',
    author_name: 'Nora',
    icon: '💬',
    icon_background: '#F4F3FF',
    mode: AppModeEnum.WORKFLOW,
    created_at: 1778622000,
    updated_at: 1778622000,
  },
  {
    ...mockAppBase,
    id: 'mock-app-data-cleanup',
    name: 'Data Cleanup Assistant',
    description: 'Normalizes messy CSV columns, suggests validation rules, and explains transformation steps.',
    author_name: 'Leo',
    icon: '🧹',
    icon_background: '#F0FDF4',
    mode: AppModeEnum.CHAT,
    created_at: 1778618400,
    updated_at: 1778618400,
  },
  {
    ...mockAppBase,
    id: 'mock-app-onboarding-guide',
    name: 'Onboarding Guide',
    description: 'Creates role-specific onboarding checklists and answers common first-week questions.',
    author_name: 'Ivy',
    icon: '🧭',
    icon_background: '#FFFBEB',
    mode: AppModeEnum.ADVANCED_CHAT,
    created_at: 1778614800,
    updated_at: 1778614800,
  },
]
