name: "🕷️ Bug report"
description: Report errors or unexpected behavior [please use English :）]
labels:
- bug
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/langgenius/dify/issues) before filing a new one!
- type: input
  attributes:
    label: Dify version
    placeholder: 0.3.21
    description: See about section in Dify console
  validations:
    required: true

- type: dropdown
  attributes:
    label: Cloud or Self Hosted
    description: How / Where was Dify installed from?
    multiple: true
    options:
      - Cloud
      - Self Hosted
      - Other (please specify in "Steps to Reproduce")
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots and a bug report log.
    placeholder: Having detailed steps helps us reproduce the bug. 
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false
