"""Durable IM message inbox domain contracts."""

from .contracts import (
    IM_INBOX_PROVIDER_METADATA_MAX_LENGTH,
    AcceptanceKind,
    ClaimToken,
    ConsumerDecision,
    IMInboxConsumer,
    IMInboxDelivery,
    IMInboxRecordId,
    IMMessageInboxRepository,
    InboxAcceptance,
    InboxBacklog,
    InboxClaimOrigin,
    InboxEventValidationError,
    InboxPersistenceError,
    InboxProcessingStatus,
    LostLease,
    TransitionApplied,
    TransitionResult,
    validate_inbox_event,
    validate_inbox_provider_tenant_id,
)

__all__ = [
    "IM_INBOX_PROVIDER_METADATA_MAX_LENGTH",
    "AcceptanceKind",
    "ClaimToken",
    "ConsumerDecision",
    "IMInboxConsumer",
    "IMInboxDelivery",
    "IMInboxRecordId",
    "IMMessageInboxRepository",
    "InboxAcceptance",
    "InboxBacklog",
    "InboxClaimOrigin",
    "InboxEventValidationError",
    "InboxPersistenceError",
    "InboxProcessingStatus",
    "LostLease",
    "TransitionApplied",
    "TransitionResult",
    "validate_inbox_event",
    "validate_inbox_provider_tenant_id",
]
