services:
  api:
    image: ${DIFY_ENTERPRISE_API_IMAGE:-dify-api-enterprise}:${DIFY_ENTERPRISE_VERSION:-local}
    build:
      context: ../api
      dockerfile: Dockerfile
      args:
        COMMIT_SHA: ${DIFY_ENTERPRISE_VERSION:-local}
    environment:
      HOME: ${HOME_OVERRIDE:-/tmp}
      ENTERPRISE_ENABLED: ${ENTERPRISE_ENABLED:-false}
      PLATFORM_ADMIN_EMAILS: ${PLATFORM_ADMIN_EMAILS:-}
      ALLOW_REGISTER: ${ALLOW_REGISTER:-false}
      ALLOW_CREATE_WORKSPACE: ${ALLOW_CREATE_WORKSPACE:-false}

  worker:
    image: ${DIFY_ENTERPRISE_API_IMAGE:-dify-api-enterprise}:${DIFY_ENTERPRISE_VERSION:-local}
    build:
      context: ../api
      dockerfile: Dockerfile
      args:
        COMMIT_SHA: ${DIFY_ENTERPRISE_VERSION:-local}
    environment:
      HOME: ${HOME_OVERRIDE:-/tmp}
      ENTERPRISE_ENABLED: ${ENTERPRISE_ENABLED:-false}
      PLATFORM_ADMIN_EMAILS: ${PLATFORM_ADMIN_EMAILS:-}
      ALLOW_REGISTER: ${ALLOW_REGISTER:-false}
      ALLOW_CREATE_WORKSPACE: ${ALLOW_CREATE_WORKSPACE:-false}

  worker_beat:
    image: ${DIFY_ENTERPRISE_API_IMAGE:-dify-api-enterprise}:${DIFY_ENTERPRISE_VERSION:-local}
    build:
      context: ../api
      dockerfile: Dockerfile
      args:
        COMMIT_SHA: ${DIFY_ENTERPRISE_VERSION:-local}
    environment:
      HOME: ${HOME_OVERRIDE:-/tmp}
      ENTERPRISE_ENABLED: ${ENTERPRISE_ENABLED:-false}
      PLATFORM_ADMIN_EMAILS: ${PLATFORM_ADMIN_EMAILS:-}
      ALLOW_REGISTER: ${ALLOW_REGISTER:-false}
      ALLOW_CREATE_WORKSPACE: ${ALLOW_CREATE_WORKSPACE:-false}

  api_websocket:
    image: ${DIFY_ENTERPRISE_API_IMAGE:-dify-api-enterprise}:${DIFY_ENTERPRISE_VERSION:-local}
    build:
      context: ../api
      dockerfile: Dockerfile
      args:
        COMMIT_SHA: ${DIFY_ENTERPRISE_VERSION:-local}
    environment:
      HOME: ${HOME_OVERRIDE:-/tmp}
      ENTERPRISE_ENABLED: ${ENTERPRISE_ENABLED:-false}
      PLATFORM_ADMIN_EMAILS: ${PLATFORM_ADMIN_EMAILS:-}
      ALLOW_REGISTER: ${ALLOW_REGISTER:-false}
      ALLOW_CREATE_WORKSPACE: ${ALLOW_CREATE_WORKSPACE:-false}

  web:
    image: ${DIFY_ENTERPRISE_WEB_IMAGE:-dify-web-enterprise}:${DIFY_ENTERPRISE_VERSION:-local}
    build:
      context: ${DIFY_WEB_BUILD_CONTEXT:-..}
      dockerfile: web/Dockerfile
      args:
        COMMIT_SHA: ${DIFY_ENTERPRISE_VERSION:-local}
    environment:
      DIFY_INTERNAL_API_URL: ${DIFY_INTERNAL_API_URL:-http://api:5001}
