// @generated by scripts/generate-command-tree.ts — DO NOT EDIT.
// Regenerate via `pnpm tree:gen`. Drift gated by `pnpm tree:check` in CI.

import type { CommandTree } from '@/plugins/commands/registry'
import CacheClear from '@/commands/cache/clear/index'
import CacheRefresh from '@/commands/cache/refresh/index'
import Call from '@/commands/call/index'
import ConfigGet from '@/commands/config/get/index'
import ConfigSet from '@/commands/config/set/index'
import ConfigUnset from '@/commands/config/unset/index'
import Login from '@/commands/login/index'
import Logout from '@/commands/logout/index'
import OpsDescribe from '@/commands/ops/describe/index'
import Ops from '@/commands/ops/index'
import SkillsInstall from '@/commands/skills/install/index'
import SkillsList from '@/commands/skills/list/index'
import Version from '@/commands/version/index'
import WorkspaceList from '@/commands/workspace/list/index'
import WorkspaceUse from '@/commands/workspace/use/index'

export const commandTree: CommandTree = {
  cache: {
    subcommands: {
      clear: { command: CacheClear, subcommands: {} },
      refresh: { command: CacheRefresh, subcommands: {} },
    },
  },
  call: { command: Call, subcommands: {} },
  config: {
    subcommands: {
      get: { command: ConfigGet, subcommands: {} },
      set: { command: ConfigSet, subcommands: {} },
      unset: { command: ConfigUnset, subcommands: {} },
    },
  },
  login: { command: Login, subcommands: {} },
  logout: { command: Logout, subcommands: {} },
  ops: {
    command: Ops,
    subcommands: {
      describe: { command: OpsDescribe, subcommands: {} },
    },
  },
  skills: {
    subcommands: {
      install: { command: SkillsInstall, subcommands: {} },
      list: { command: SkillsList, subcommands: {} },
    },
  },
  version: { command: Version, subcommands: {} },
  workspace: {
    subcommands: {
      list: { command: WorkspaceList, subcommands: {} },
      use: { command: WorkspaceUse, subcommands: {} },
    },
  },
}
