// @generated by scripts/generate-command-tree.ts — DO NOT EDIT.
// Regenerate via `pnpm tree:gen`. Drift gated by `pnpm tree:check` in CI.

import type { CommandTree } from '@/framework/registry'
import AuthDevicesList from '@/commands/auth/devices/list/index'
import AuthDevicesRevoke from '@/commands/auth/devices/revoke/index'
import AuthLogin from '@/commands/auth/login/index'
import AuthLogout from '@/commands/auth/logout/index'
import AuthStatus from '@/commands/auth/status/index'
import AuthWhoami from '@/commands/auth/whoami/index'
import ConfigGet from '@/commands/config/get/index'
import ConfigPath from '@/commands/config/path/index'
import ConfigSet from '@/commands/config/set/index'
import ConfigUnset from '@/commands/config/unset/index'
import ConfigView from '@/commands/config/view/index'
import CreateMember from '@/commands/create/member/index'
import DeleteMember from '@/commands/delete/member/index'
import DescribeApp from '@/commands/describe/app/index'
import EnvList from '@/commands/env/list/index'
import GetApp from '@/commands/get/app/index'
import GetMember from '@/commands/get/member/index'
import GetWorkspace from '@/commands/get/workspace/index'
import HelpAccount from '@/commands/help/account/index'
import HelpEnvironment from '@/commands/help/environment/index'
import HelpExternal from '@/commands/help/external/index'
import ResumeApp from '@/commands/resume/app/index'
import RunApp from '@/commands/run/app/index'
import SetMember from '@/commands/set/member/index'
import UseWorkspace from '@/commands/use/workspace/index'
import Version from '@/commands/version/index'

export const commandTree: CommandTree = {
  auth: {
    subcommands: {
      devices: {
        subcommands: {
          list: { command: AuthDevicesList, subcommands: {} },
          revoke: { command: AuthDevicesRevoke, subcommands: {} },
        },
      },
      login: { command: AuthLogin, subcommands: {} },
      logout: { command: AuthLogout, subcommands: {} },
      status: { command: AuthStatus, subcommands: {} },
      whoami: { command: AuthWhoami, subcommands: {} },
    },
  },
  config: {
    subcommands: {
      get: { command: ConfigGet, subcommands: {} },
      path: { command: ConfigPath, subcommands: {} },
      set: { command: ConfigSet, subcommands: {} },
      unset: { command: ConfigUnset, subcommands: {} },
      view: { command: ConfigView, subcommands: {} },
    },
  },
  create: {
    subcommands: {
      member: { command: CreateMember, subcommands: {} },
    },
  },
  delete: {
    subcommands: {
      member: { command: DeleteMember, subcommands: {} },
    },
  },
  describe: {
    subcommands: {
      app: { command: DescribeApp, subcommands: {} },
    },
  },
  env: {
    subcommands: {
      list: { command: EnvList, subcommands: {} },
    },
  },
  get: {
    subcommands: {
      app: { command: GetApp, subcommands: {} },
      member: { command: GetMember, subcommands: {} },
      workspace: { command: GetWorkspace, subcommands: {} },
    },
  },
  help: {
    subcommands: {
      account: { command: HelpAccount, subcommands: {} },
      environment: { command: HelpEnvironment, subcommands: {} },
      external: { command: HelpExternal, subcommands: {} },
    },
  },
  resume: {
    subcommands: {
      app: { command: ResumeApp, subcommands: {} },
    },
  },
  run: {
    subcommands: {
      app: { command: RunApp, subcommands: {} },
    },
  },
  set: {
    subcommands: {
      member: { command: SetMember, subcommands: {} },
    },
  },
  use: {
    subcommands: {
      workspace: { command: UseWorkspace, subcommands: {} },
    },
  },
  version: { command: Version, subcommands: {} },
}
