// Switch to the %SYS namespace to modify system settings
set $namespace="%SYS"

// Set predefined user passwords to never expire (default password: SYS)
Do ##class(Security.Users).UnExpireUserPasswords("*")

// Change the default password　
Do $SYSTEM.Security.ChangePassword("_SYSTEM","Dify@1234")

// Install the Japanese locale (default is English since the container is Ubuntu-based)
// Do ##class(Config.NLS.Locales).Install("jpuw")
