# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ruby-client.gemspec
gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.0"

gem "rubocop", "~> 0.80"
