import { BlockEnum } from '../../types'

const data = [
  [
    {
      id: '1',
      index: 1,
      predecessor_node_id: '0',
      node_id: '1',
      node_type: BlockEnum.Code,
      title: 'code',
      inputs: {},
      process_data: {},
      outputs: {},
      status: 'completed',
      error: '',
      elapsed_time: 0,
      execution_metadata: {
        total_tokens: 0,
        total_price: 0,
        currency: '',
      },
      created_at: 0,
      created_by: {
        id: '1',
        name: 'name',
        email: 'email',
      },
      finished_at: 0,
      extras: {},
      expand: false,
    },
    {
      id: '2',
      index: 1,
      predecessor_node_id: '0',
      node_id: '1',
      node_type: BlockEnum.End,
      title: 'code',
      inputs: {},
      process_data: {},
      outputs: {},
      status: 'running',
      error: '',
      elapsed_time: 0,
      execution_metadata: {
        total_tokens: 0,
        total_price: 0,
        currency: '',
      },
      created_at: 0,
      created_by: {
        id: '1',
        name: 'name',
        email: 'email',
      },
      finished_at: 0,
      extras: {},
      expand: false,
    },
  ],
  [
    {
      id: '1',
      index: 1,
      predecessor_node_id: '0',
      node_id: '1',
      node_type: BlockEnum.Code,
      title: 'code',
      inputs: {},
      process_data: {},
      outputs: {},
      status: 'running',
      error: '',
      elapsed_time: 0,
      execution_metadata: {
        total_tokens: 0,
        total_price: 0,
        currency: '',
      },
      created_at: 0,
      created_by: {
        id: '1',
        name: 'name',
        email: 'email',
      },
      finished_at: 0,
      extras: {},
      expand: false,
    },
  ],
]

export default data
