"""Synchronous initializer that compiles draft app assets.

Unlike ``AppAssetsInitializer`` (which downloads a pre-built ZIP for
published assets), this initializer runs the build pipeline on the fly
so that ``.md`` skill documents are compiled and their resolved content
is embedded directly into the download script — avoiding the S3
round-trip that was previously required for resolved keys.

Execution order:
    ``DraftAppAssetsInitializer`` (sync) compiles assets and publishes
    the ``SkillBundle`` to ``sandbox.attrs`` in-memory, so the
    downstream ``SkillInitializer`` can skip the Redis/S3 round-trip.
    ``DraftAppAssetsDownloader`` (async) then pushes the compiled
    artefacts into the sandbox VM in the background.
"""

import logging

from core.app_assets.builder.base import BuildContext
from core.app_assets.builder.file_builder import FileBuilder
from core.app_assets.builder.pipeline import AssetBuildPipeline
from core.app_assets.builder.skill_builder import SkillBuilder
from core.app_assets.constants import AppAssetsAttrs
from core.sandbox.entities import AppAssets
from core.sandbox.sandbox import Sandbox
from core.sandbox.services import AssetDownloadService
from core.skill import SkillAttrs
from core.virtual_environment.__base.helpers import pipeline
from services.app_asset_service import AppAssetService

from .base import AsyncSandboxInitializer, SandboxInitializeContext, SyncSandboxInitializer

logger = logging.getLogger(__name__)


class DraftAppAssetsInitializer(SyncSandboxInitializer):
    """Compile draft assets and publish the ``SkillBundle`` to attrs.

    The build pipeline compiles ``.md`` skill files in-process.
    The resulting ``SkillBundle`` is persisted to Redis/S3 (by
    ``SkillBuilder``) **and** written to ``sandbox.attrs[BUNDLE]``
    so that ``SkillInitializer`` can read it without a round-trip.
    Built asset items are stored on ``ctx.built_assets`` for the
    async ``DraftAppAssetsDownloader`` to consume.
    """

    def initialize(self, sandbox: Sandbox, ctx: SandboxInitializeContext) -> None:
        tree = sandbox.attrs.get(AppAssetsAttrs.FILE_TREE)

        # --- 1. Run the build pipeline (SkillBuilder compiles .md inline) ---
        accessor = AppAssetService.get_accessor(ctx.tenant_id, ctx.app_id)
        skill_builder = SkillBuilder(accessor=accessor)
        build_pipeline = AssetBuildPipeline([skill_builder, FileBuilder()])
        build_ctx = BuildContext(tenant_id=ctx.tenant_id, app_id=ctx.app_id, build_id=ctx.assets_id)
        built_assets = build_pipeline.build_all(tree, build_ctx)
        ctx.built_assets = built_assets

        # Publish the in-memory bundle so SkillInitializer skips Redis/S3.
        if skill_builder.bundle is not None:
            sandbox.attrs.set(SkillAttrs.BUNDLE, skill_builder.bundle)


class DraftAppAssetsDownloader(AsyncSandboxInitializer):
    """Download the compiled assets into the sandbox VM.

    The download script is generated by ``DraftAppAssetsInitializer`` and
    includes inline base64 content for compiled skills, as well as
    presigned URLs for other files.
    """

    _TIMEOUT = 600  # 10 minutes

    def initialize(self, sandbox: Sandbox, ctx: SandboxInitializeContext) -> None:
        if not ctx.built_assets:
            logger.debug("No built assets found for assets_id=%s", ctx.assets_id)
            return

        download_items = AppAssetService.to_download_items(ctx.built_assets)
        script = AssetDownloadService.build_download_script(download_items, AppAssets.PATH)
        pipeline(sandbox.vm).add(
            ["sh", "-c", script],
            error_message="Failed to download draft assets",
        ).execute(timeout=self._TIMEOUT, raise_on_error=True)

        logger.info(
            "Draft app assets initialized for app_id=%s, assets_id=%s",
            ctx.app_id,
            ctx.assets_id,
        )
