from typing import Any

class Request:
    @property
    def args(self) -> Any: ...
    @property
    def cookies(self) -> Any: ...
    @property
    def headers(self) -> Any: ...
    @property
    def path(self) -> str: ...
    @property
    def full_path(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def base_url(self) -> str: ...
    @property
    def query_string(self) -> bytes: ...
