"""Infrastructure-free IM configuration, synchronization, and binding boundary.

This package depends on canonical Contact Directory facts and shared primitive
values. Provider clients, controllers, SQLAlchemy sessions, ORM records, and
provider transport payload types belong outside this boundary. The public API
hides configuration CAS, sync matching, and effective-binding priority behind
domain decisions and transaction-oriented ports.
"""

from .binding_commands import ContactIMBindingView, IMBindingCommandError, IMBindingCommandErrorCode
from .binding_resolution import (
    BindingResolutionKind,
    BindingResolutionResult,
    EffectiveBindingResolver,
    EffectiveIMBindingSnapshot,
)
from .change_log import (
    IMBindingChangeSnapshot,
    IMIdentityChangeSnapshot,
    IMReconciliationChange,
    IMReconciliationOperation,
    IMReconciliationSnapshot,
    IMReconciliationSubjectKind,
)
from .integration import (
    ConfigurationTransition,
    ConfigurationTransitionKind,
    CurrentStateInvalidation,
    EncryptedCredentials,
    IMIntegration,
    IMIntegrationView,
    IntegrationDeletion,
    IntegrationRevisionToken,
    ProviderTenantIdentity,
    StaleRevision,
)
from .management import (
    ConfirmedIMConfiguration,
    IMIntegrationAlreadyExistsError,
    IMProviderConfigurationFailureKind,
    IMProviderConfigurationPort,
    IMProviderCredentials,
    IMProviderTestResult,
)
from .ports import (
    ActiveRunDecision,
    ActiveRunDecisionKind,
    ApplyReconciliationResult,
    ApplyReconciliationStatus,
    IMControlPlanePersistenceError,
    IMControlPlaneRepository,
    IMSyncRepository,
    ResolvedReconciliationWarning,
)
from .records import IMBinding, IMIdentity, OpaqueProviderPayload
from .state import IMIntegrationState
from .sync_reconciliation import (
    BlockedReconciliation,
    ContactEmailMatchState,
    CreateIMBinding,
    CurrentIMBindingState,
    CurrentIMIdentityState,
    DeleteIMBinding,
    ExistingIMIdentityRef,
    IMBindingMutation,
    IMIdentityDeletion,
    IMIdentityRef,
    IMIdentityUpsert,
    IMIdentityUpsertKind,
    NewIMIdentityRef,
    PlanGenerationResult,
    PlannedReconciliationWarning,
    PlannedSyncResult,
    ReconciliationBlock,
    ReconciliationBlockCode,
    ReconciliationInput,
    ReconciliationPlan,
    ReconciliationReasonCode,
    ReconciliationRunRef,
    ReplaceIMBinding,
    SyncReconciler,
)
from .sync_records import (
    IMSyncRun,
    SyncContactSnapshot,
    SynchronizedIMIdentity,
    SynchronizedIMIdentityPage,
    SyncIdentitySnapshot,
    SyncResultFact,
    SyncResultPage,
)

__all__ = [
    "ActiveRunDecision",
    "ActiveRunDecisionKind",
    "ApplyReconciliationResult",
    "ApplyReconciliationStatus",
    "BindingResolutionKind",
    "BindingResolutionResult",
    "BlockedReconciliation",
    "ConfigurationTransition",
    "ConfigurationTransitionKind",
    "ConfirmedIMConfiguration",
    "ContactEmailMatchState",
    "ContactIMBindingView",
    "CreateIMBinding",
    "CurrentIMBindingState",
    "CurrentIMIdentityState",
    "CurrentStateInvalidation",
    "DeleteIMBinding",
    "EffectiveBindingResolver",
    "EffectiveIMBindingSnapshot",
    "EncryptedCredentials",
    "ExistingIMIdentityRef",
    "IMBinding",
    "IMBindingChangeSnapshot",
    "IMBindingCommandError",
    "IMBindingCommandErrorCode",
    "IMBindingMutation",
    "IMControlPlanePersistenceError",
    "IMControlPlaneRepository",
    "IMIdentity",
    "IMIdentityChangeSnapshot",
    "IMIdentityDeletion",
    "IMIdentityRef",
    "IMIdentityUpsert",
    "IMIdentityUpsertKind",
    "IMIntegration",
    "IMIntegrationAlreadyExistsError",
    "IMIntegrationState",
    "IMIntegrationView",
    "IMProviderConfigurationFailureKind",
    "IMProviderConfigurationPort",
    "IMProviderCredentials",
    "IMProviderTestResult",
    "IMReconciliationChange",
    "IMReconciliationOperation",
    "IMReconciliationSnapshot",
    "IMReconciliationSubjectKind",
    "IMSyncRepository",
    "IMSyncRun",
    "IntegrationDeletion",
    "IntegrationRevisionToken",
    "NewIMIdentityRef",
    "OpaqueProviderPayload",
    "PlanGenerationResult",
    "PlannedReconciliationWarning",
    "PlannedSyncResult",
    "ProviderTenantIdentity",
    "ReconciliationBlock",
    "ReconciliationBlockCode",
    "ReconciliationInput",
    "ReconciliationPlan",
    "ReconciliationReasonCode",
    "ReconciliationRunRef",
    "ReplaceIMBinding",
    "ResolvedReconciliationWarning",
    "StaleRevision",
    "SyncContactSnapshot",
    "SyncIdentitySnapshot",
    "SyncReconciler",
    "SyncResultFact",
    "SyncResultPage",
    "SynchronizedIMIdentity",
    "SynchronizedIMIdentityPage",
]
