SYSTEM_VARIABLE_NODE_ID = "sys"
ENVIRONMENT_VARIABLE_NODE_ID = "env"
CONVERSATION_VARIABLE_NODE_ID = "conversation"
RAG_PIPELINE_VARIABLE_NODE_ID = "rag"

CHILD_SYNC_VARIABLE_NODE_IDS = frozenset((CONVERSATION_VARIABLE_NODE_ID,))
