"""Stable Human Input v2 values shared across domain contexts.

This package contains infrastructure-free values only. Feature-specific ownership
and lifecycle rules belong to their bounded context rather than this package.
"""

from .values import (
    AccountId,
    AppId,
    ApproverGrantId,
    AuditEventId,
    ContactId,
    DeliveryAttemptId,
    DeliveryEndpointId,
    DeploymentScope,
    DirectoryScope,
    EmailProviderId,
    EndUserId,
    FormId,
    IMBindingId,
    IMIdentityId,
    IMSyncResultId,
    IMSyncRunId,
    IntegrationId,
    NormalizedEmail,
    OTPChallengeId,
    PlatformEntryId,
    SubmissionId,
    UploadCapabilityId,
    UploadFileAssociationId,
    WorkspaceId,
    WorkspaceScope,
)

__all__ = [
    "AccountId",
    "AppId",
    "ApproverGrantId",
    "AuditEventId",
    "ContactId",
    "DeliveryAttemptId",
    "DeliveryEndpointId",
    "DeploymentScope",
    "DirectoryScope",
    "EmailProviderId",
    "EndUserId",
    "FormId",
    "IMBindingId",
    "IMIdentityId",
    "IMSyncResultId",
    "IMSyncRunId",
    "IntegrationId",
    "NormalizedEmail",
    "OTPChallengeId",
    "PlatformEntryId",
    "SubmissionId",
    "UploadCapabilityId",
    "UploadFileAssociationId",
    "WorkspaceId",
    "WorkspaceScope",
]
