export const listData = [
  {
    id: 'fdjklajfkljadslf',
    author: 'KVOJJJin',
    name: 'GOGOGO',
    icon: 'https://cloud.dify.dev/console/api/workspaces/694cc430-fa36-4458-86a0-4a98c09c4684/model-providers/langgenius/openai/openai/icon_large/en_US',
    server_url: 'https://mcp.composio.dev/notion/****/abc',
    type: 'mcp',
    is_team_authorization: false,
    tools: ['aaa', 'bbb'],
    update_elapsed_time: 1742892299,
  },
  {
    id: 'fdjklajfkljadslf',
    author: 'KVOJJJin',
    name: 'GOGOGO2',
    icon: 'https://cloud.dify.dev/console/api/workspaces/694cc430-fa36-4458-86a0-4a98c09c4684/model-providers/langgenius/openai/openai/icon_large/en_US',
    server_url: 'https://mcp.composio.dev/notion/****/abc',
    type: 'mcp',
    is_team_authorization: false,
    tools: ['aaa', 'bbb'],
    update_elapsed_time: 1742892299,
  },
  {
    id: 'fdjklajfkljadslf',
    author: 'KVOJJJin',
    name: 'GOGOGO3',
    icon: 'https://cloud.dify.dev/console/api/workspaces/694cc430-fa36-4458-86a0-4a98c09c4684/model-providers/langgenius/openai/openai/icon_large/en_US',
    server_url: 'https://mcp.composio.dev/notion/****/abc',
    type: 'mcp',
    is_team_authorization: false,
    tools: ['aaa', 'bbb'],
    update_elapsed_time: 1742892299,
  },
]
