// GENERATE BY script
// DON NOT EDIT IT MANUALLY
//
// Generated from: https://raw.githubusercontent.com/langgenius/dify-docs/refs/heads/main/docs.json
// Generated at: 2026-01-12T07:59:44.775Z

// Language prefixes
export type DocLanguage = 'en' | 'zh' | 'ja'

// UseDify paths
export type UseDifyPath =
  | 'use-dify/build/additional-features'
  | 'use-dify/build/goto-anything'
  | 'use-dify/build/mcp'
  | 'use-dify/build/orchestrate-node'
  | 'use-dify/build/predefined-error-handling-logic'
  | 'use-dify/build/shortcut-key'
  | 'use-dify/build/version-control'
  | 'use-dify/debug/error-type'
  | 'use-dify/debug/history-and-logs'
  | 'use-dify/debug/step-run'
  | 'use-dify/debug/variable-inspect'
  | 'use-dify/getting-started/introduction'
  | 'use-dify/getting-started/key-concepts'
  | 'use-dify/getting-started/quick-start'
  | 'use-dify/knowledge/connect-external-knowledge-base'
  | 'use-dify/knowledge/create-knowledge/chunking-and-cleaning-text'
  | 'use-dify/knowledge/create-knowledge/import-text-data/readme'
  | 'use-dify/knowledge/create-knowledge/import-text-data/sync-from-notion'
  | 'use-dify/knowledge/create-knowledge/import-text-data/sync-from-website'
  | 'use-dify/knowledge/create-knowledge/introduction'
  | 'use-dify/knowledge/create-knowledge/setting-indexing-methods'
  | 'use-dify/knowledge/external-knowledge-api'
  | 'use-dify/knowledge/integrate-knowledge-within-application'
  | 'use-dify/knowledge/knowledge-pipeline/authorize-data-source'
  | 'use-dify/knowledge/knowledge-pipeline/create-knowledge-pipeline'
  | 'use-dify/knowledge/knowledge-pipeline/knowledge-pipeline-orchestration'
  | 'use-dify/knowledge/knowledge-pipeline/manage-knowledge-base'
  | 'use-dify/knowledge/knowledge-pipeline/publish-knowledge-pipeline'
  | 'use-dify/knowledge/knowledge-pipeline/readme'
  | 'use-dify/knowledge/knowledge-pipeline/upload-files'
  | 'use-dify/knowledge/knowledge-request-rate-limit'
  | 'use-dify/knowledge/manage-knowledge/introduction'
  | 'use-dify/knowledge/manage-knowledge/maintain-dataset-via-api'
  | 'use-dify/knowledge/manage-knowledge/maintain-knowledge-documents'
  | 'use-dify/knowledge/metadata'
  | 'use-dify/knowledge/readme'
  | 'use-dify/knowledge/test-retrieval'
  | 'use-dify/monitor/analysis'
  | 'use-dify/monitor/annotation-reply'
  | 'use-dify/monitor/integrations/integrate-aliyun'
  | 'use-dify/monitor/integrations/integrate-arize'
  | 'use-dify/monitor/integrations/integrate-langfuse'
  | 'use-dify/monitor/integrations/integrate-langsmith'
  | 'use-dify/monitor/integrations/integrate-opik'
  | 'use-dify/monitor/integrations/integrate-phoenix'
  | 'use-dify/monitor/integrations/integrate-weave'
  | 'use-dify/monitor/logs'
  | 'use-dify/nodes/agent'
  | 'use-dify/nodes/answer'
  | 'use-dify/nodes/code'
  | 'use-dify/nodes/doc-extractor'
  | 'use-dify/nodes/http-request'
  | 'use-dify/nodes/ifelse'
  | 'use-dify/nodes/iteration'
  | 'use-dify/nodes/knowledge-retrieval'
  | 'use-dify/nodes/list-operator'
  | 'use-dify/nodes/llm'
  | 'use-dify/nodes/loop'
  | 'use-dify/nodes/output'
  | 'use-dify/nodes/parameter-extractor'
  | 'use-dify/nodes/question-classifier'
  | 'use-dify/nodes/template'
  | 'use-dify/nodes/tools'
  | 'use-dify/nodes/trigger/overview'
  | 'use-dify/nodes/trigger/plugin-trigger'
  | 'use-dify/nodes/trigger/schedule-trigger'
  | 'use-dify/nodes/trigger/webhook-trigger'
  | 'use-dify/nodes/user-input'
  | 'use-dify/nodes/variable-aggregator'
  | 'use-dify/nodes/variable-assigner'
  | 'use-dify/publish/README'
  | 'use-dify/publish/developing-with-apis'
  | 'use-dify/publish/publish-mcp'
  | 'use-dify/publish/webapp/chatflow-webapp'
  | 'use-dify/publish/webapp/embedding-in-websites'
  | 'use-dify/publish/webapp/web-app-access'
  | 'use-dify/publish/webapp/web-app-settings'
  | 'use-dify/publish/webapp/workflow-webapp'
  | 'use-dify/tutorials/article-reader'
  | 'use-dify/tutorials/build-ai-image-generation-app'
  | 'use-dify/tutorials/customer-service-bot'
  | 'use-dify/tutorials/simple-chatbot'
  | 'use-dify/tutorials/twitter-chatflow'
  | 'use-dify/workspace/app-management'
  | 'use-dify/workspace/model-providers'
  | 'use-dify/workspace/personal-account-management'
  | 'use-dify/workspace/plugins'
  | 'use-dify/workspace/readme'
  | 'use-dify/workspace/subscription-management'
  | 'use-dify/workspace/team-members-management'

// SelfHost paths
export type SelfHostPath =
  | 'self-host/advanced-deployments/local-source-code'
  | 'self-host/advanced-deployments/start-the-frontend-docker-container'
  | 'self-host/configuration/environments'
  | 'self-host/platform-guides/bt-panel'
  | 'self-host/platform-guides/dify-premium'
  | 'self-host/quick-start/docker-compose'
  | 'self-host/quick-start/faqs'
  | 'self-host/troubleshooting/common-issues'
  | 'self-host/troubleshooting/docker-issues'
  | 'self-host/troubleshooting/integrations'
  | 'self-host/troubleshooting/storage-and-migration'
  | 'self-host/troubleshooting/weaviate-v4-migration'

// DevelopPlugin paths
export type DevelopPluginPath =
  | 'develop-plugin/dev-guides-and-walkthroughs/agent-strategy-plugin'
  | 'develop-plugin/dev-guides-and-walkthroughs/cheatsheet'
  | 'develop-plugin/dev-guides-and-walkthroughs/creating-new-model-provider'
  | 'develop-plugin/dev-guides-and-walkthroughs/datasource-plugin'
  | 'develop-plugin/dev-guides-and-walkthroughs/develop-a-slack-bot-plugin'
  | 'develop-plugin/dev-guides-and-walkthroughs/develop-flomo-plugin'
  | 'develop-plugin/dev-guides-and-walkthroughs/develop-md-exporter'
  | 'develop-plugin/dev-guides-and-walkthroughs/develop-multimodal-data-processing-tool'
  | 'develop-plugin/dev-guides-and-walkthroughs/endpoint'
  | 'develop-plugin/dev-guides-and-walkthroughs/tool-oauth'
  | 'develop-plugin/dev-guides-and-walkthroughs/tool-plugin'
  | 'develop-plugin/dev-guides-and-walkthroughs/trigger-plugin'
  | 'develop-plugin/features-and-specs/advanced-development/bundle'
  | 'develop-plugin/features-and-specs/advanced-development/customizable-model'
  | 'develop-plugin/features-and-specs/advanced-development/reverse-invocation'
  | 'develop-plugin/features-and-specs/advanced-development/reverse-invocation-app'
  | 'develop-plugin/features-and-specs/advanced-development/reverse-invocation-model'
  | 'develop-plugin/features-and-specs/advanced-development/reverse-invocation-node'
  | 'develop-plugin/features-and-specs/advanced-development/reverse-invocation-tool'
  | 'develop-plugin/features-and-specs/plugin-types/general-specifications'
  | 'develop-plugin/features-and-specs/plugin-types/model-designing-rules'
  | 'develop-plugin/features-and-specs/plugin-types/model-schema'
  | 'develop-plugin/features-and-specs/plugin-types/multilingual-readme'
  | 'develop-plugin/features-and-specs/plugin-types/persistent-storage-kv'
  | 'develop-plugin/features-and-specs/plugin-types/plugin-info-by-manifest'
  | 'develop-plugin/features-and-specs/plugin-types/plugin-logging'
  | 'develop-plugin/features-and-specs/plugin-types/remote-debug-a-plugin'
  | 'develop-plugin/features-and-specs/plugin-types/tool'
  | 'develop-plugin/getting-started/cli'
  | 'develop-plugin/getting-started/getting-started-dify-plugin'
  | 'develop-plugin/publishing/faq/faq'
  | 'develop-plugin/publishing/marketplace-listing/plugin-auto-publish-pr'
  | 'develop-plugin/publishing/marketplace-listing/release-by-file'
  | 'develop-plugin/publishing/marketplace-listing/release-overview'
  | 'develop-plugin/publishing/marketplace-listing/release-to-dify-marketplace'
  | 'develop-plugin/publishing/marketplace-listing/release-to-individual-github-repo'
  | 'develop-plugin/publishing/standards/contributor-covenant-code-of-conduct'
  | 'develop-plugin/publishing/standards/privacy-protection-guidelines'
  | 'develop-plugin/publishing/standards/third-party-signature-verification'

// API Reference paths
export type ApiReferencePath =
  | 'api-reference/openapi_chat.json'
  | 'api-reference/openapi_chatflow.json'
  | 'api-reference/openapi_workflow.json'
  | 'api-reference/openapi_knowledge.json'
  | 'api-reference/openapi_completion.json'

// Base path without language prefix
export type DocPathWithoutLangBase =
  | UseDifyPath
  | SelfHostPath
  | DevelopPluginPath
  | ApiReferencePath

// Combined path without language prefix (supports optional #anchor)
export type DocPathWithoutLang =
  | DocPathWithoutLangBase
  | `${DocPathWithoutLangBase}#${string}`

// Full documentation path with language prefix
export type DifyDocPath = `${DocLanguage}/${DocPathWithoutLang}`
