name: Setup Web Environment

runs:
  using: composite
  steps:
    - name: Setup Vite+
      uses: hyoban/setup-vp@f9d7995abfba8d826a79ba2496ff603a503af04b # v1.3.0
      with:
        working-directory: web
        node-version-file: .nvmrc
        cache: true
        run-install: true
