name: Setup Web Environment
description: A GitHub Action to set up the web environment using Vite+.

runs:
  using: composite
  steps:
    - name: Setup Vite+
      uses: hyoban/setup-vp@96511aa421048609564ade4427c73d0078d4afc1 # v1.3.0
      with:
        node-version-file: .nvmrc
        cache: true
        run-install: true
