"""add created_by to api_tokens

Revision ID: 8db4e7683504
Revises: 01d6889832f7
Create Date: 2024-12-07 19:36:49.632151

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db4e7683504'
down_revision = '01d6889832f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', models.types.StringUUID(), nullable=True))
        batch_op.create_index('api_token_created_by_idx', ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('api_token_created_by_idx')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
