"""message regenerate

Revision ID: b194ab4e3c69
Revises: 2dbe42621d96
Create Date: 2024-08-27 02:31:24.186377

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'b194ab4e3c69'
down_revision = '2dbe42621d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_regenerated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('parent_message_id', models.types.StringUUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('parent_message_id')
        batch_op.drop_column('is_regenerated')
    # ### end Alembic commands ###
