"""add created_by to api_tokens

Revision ID: 5f42bf0de698
Revises: 01d6889832f7
Create Date: 2024-12-06 13:24:28.701384

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f42bf0de698'
down_revision = '01d6889832f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', models.types.StringUUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_column('created_by')
    # ### end Alembic commands ###
