"""set workflow_runs.output not null

Revision ID: 30ae84e6ec75
Revises: 11b07f66c737
Create Date: 2024-12-19 17:48:32.565985

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ae84e6ec75'
down_revision = '11b07f66c737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('outputs',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('outputs',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
