"""add type column not null default tool

Revision ID: 2536f83803a8
Revises: 6bb0832495f0
Create Date: 2025-12-16 14:24:40.740253

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2536f83803a8'
down_revision = '6bb0832495f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False, server_default='tool'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
