"""remove unused is_deleted field from conversations

Revision ID: 4f02b6704509
Revises: b95962a3885c
Create Date: 2025-09-02 20:12:37.311318

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f02b6704509'
down_revision = 'b95962a3885c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete any conversations where is_deleted is true before dropping the column
    op.execute("DELETE FROM conversations WHERE is_deleted = true")
    
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
