"""add organization support

Revision ID: 18dd49e03533
Revises: ceaf4dfed584
Create Date: 2025-03-24 20:02:56.847845

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dd49e03533'
down_revision = 'ceaf4dfed584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_organization_id', models.types.StringUUID(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', models.types.StringUUID(), nullable=True))
        batch_op.create_index('conversation_organization_idx', ['organization_id'], unique=False)

    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', models.types.StringUUID(), nullable=True))
        batch_op.create_index('end_user_organization_id_idx', ['organization_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', models.types.StringUUID(), nullable=True))
        batch_op.create_index('message_organization_id_idx', ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('message_organization_id_idx')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.drop_index('end_user_organization_id_idx')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('conversation_organization_idx')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('current_organization_id')

    # ### end Alembic commands ###
