"""add workflow_run_created_at_id_idx

Revision ID: 905527cc8fd3
Revises: 03ea244985ce
Create Date: 2025-12-18 16:30:02.462084

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '905527cc8fd3'
down_revision = '03ea244985ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index('workflow_run_created_at_id_idx', ['created_at', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index('workflow_run_created_at_id_idx')
    # ### end Alembic commands ###
