"""add_pipeline_info_4

Revision ID: e4fb49a4fe86
Revises: c459994abfa8
Create Date: 2025-05-30 00:52:49.222558

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4fb49a4fe86'
down_revision = 'c459994abfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource_providers', schema=None) as batch_op:
        batch_op.alter_column('plugin_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource_providers', schema=None) as batch_op:
        batch_op.alter_column('plugin_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
