"""plugin_trigger

Revision ID: afa344924e5c
Revises: 9ee7d347f4c1
Create Date: 2025-09-02 15:28:31.426728

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa344924e5c'
down_revision = '9ee7d347f4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_provider_apps',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('app_icon', sa.String(length=255), nullable=False),
    sa.Column('app_label', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('scope', sa.String(length=255), server_default=sa.text("'read:name read:email read:avatar read:interface_language read:timezone'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='oauth_provider_app_pkey')
    )
    with op.batch_alter_table('oauth_provider_apps', schema=None) as batch_op:
        batch_op.create_index('oauth_provider_app_client_id_idx', ['client_id'], unique=False)

    op.create_table('workflow_plugin_triggers',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('trigger_id', sa.String(length=510), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='workflow_plugin_trigger_pkey'),
    sa.UniqueConstraint('app_id', 'node_id', 'triggered_by', name='uniq_plugin_node'),
    sa.UniqueConstraint('trigger_id', 'node_id', name='uniq_trigger_node')
    )
    with op.batch_alter_table('workflow_plugin_triggers', schema=None) as batch_op:
        batch_op.create_index('workflow_plugin_trigger_tenant_idx', ['tenant_id'], unique=False)
        batch_op.create_index('workflow_plugin_trigger_trigger_idx', ['trigger_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_plugin_triggers', schema=None) as batch_op:
        batch_op.drop_index('workflow_plugin_trigger_trigger_idx')
        batch_op.drop_index('workflow_plugin_trigger_tenant_idx')

    op.drop_table('workflow_plugin_triggers')
    with op.batch_alter_table('oauth_provider_apps', schema=None) as batch_op:
        batch_op.drop_index('oauth_provider_app_client_id_idx')

    op.drop_table('oauth_provider_apps')
    # ### end Alembic commands ###
