"""add account mfa settings table

Revision ID: abc123def456
Revises: 0ab65e1cc7fa
Create Date: 2025-07-08 15:00:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_mfa_settings',
    sa.Column('id', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('setup_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id', name='account_mfa_settings_pkey'),
    sa.UniqueConstraint('account_id', name='unique_account_mfa_settings')
    )
    op.create_index('account_mfa_settings_account_id_idx', 'account_mfa_settings', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account_mfa_settings_account_id_idx', table_name='account_mfa_settings')
    op.drop_table('account_mfa_settings')
    # ### end Alembic commands ###
