"""add_pipeline_info_15

Revision ID: 74e5f667f4b7
Revises: d3c68680d3ba
Create Date: 2025-07-21 15:23:20.825747

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e5f667f4b7'
down_revision = 'd3c68680d3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource_providers', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
