"""feat: add created_at id index to messages

Revision ID: 649d817a739e
Revises: 03ea244985ce
Create Date: 2025-12-18 16:39:33.090454

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '649d817a739e'
down_revision = '03ea244985ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('message_created_at_id_idx', ['created_at', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('message_created_at_id_idx')

    # ### end Alembic commands ###
