"""trigger_log_metadata

Revision ID: 5ed4b21dbb8d
Revises: 132392a2635f
Create Date: 2025-10-27 17:52:35.658975

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed4b21dbb8d'
down_revision = '132392a2635f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('workflow_trigger_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_trigger_logs', schema=None) as batch_op:
        batch_op.drop_column('trigger_metadata')

    # ### end Alembic commands ###
