"""add_pipeline_info_9

Revision ID: 15e40b74a6d2
Revises: a1025f709c06
Create Date: 2025-07-02 11:32:44.125790

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e40b74a6d2'
down_revision = 'a1025f709c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource_providers', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
