"""multiple credential

Revision ID: 222376193a49
Revises: 99310d2c25a6
Create Date: 2025-06-19 11:33:46.400455

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222376193a49'
down_revision = '99310d2c25a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_builtin_providers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_builtin_tool_provider'), type_='unique')

    with op.batch_alter_table('tool_oauth_user_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_type', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_oauth_user_clients', schema=None) as batch_op:
        batch_op.drop_column('owner_type')

    with op.batch_alter_table('tool_builtin_providers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_builtin_tool_provider'), ['tenant_id', 'provider', 'credential_type'])

    # ### end Alembic commands ###
