"""update status

Revision ID: 382f0cad6652
Revises: 329938947502
Create Date: 2025-03-31 21:15:32.929703

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f0cad6652'
down_revision = '329938947502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_generated_images', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
