"""add model_name and model_parameters to prompt_version

Revision ID: 090bb5fe6078
Revises: e3845da34e79
Create Date: 2025-06-28 16:07:29.626618

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '090bb5fe6078'
down_revision = 'e3845da34e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_column('model_parameters')
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###
