"""providers table add private_key

Revision ID: 582c477e905b
Revises: 8e00c75b3907
Create Date: 2025-05-28 10:41:31.662951

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582c477e905b'
down_revision = '8e00c75b3907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypt_private_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('encrypt_private_key')

    # ### end Alembic commands ###
