"""add page column to segment

Revision ID: 8c83edec42e8
Revises: d28f2004b072
Create Date: 2025-05-15 03:08:23.196234

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c83edec42e8'
down_revision = 'd28f2004b072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.drop_column('page_number')

    # ### end Alembic commands ###
