"""Alter table pipeline_recommended_plugins add column type

Revision ID: 6bb0832495f0
Revises: 7bb281b7a422
Create Date: 2025-12-15 16:14:38.482072

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bb0832495f0'
down_revision = '7bb281b7a422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_triggers', schema=None) as batch_op:
        batch_op.alter_column('provider_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('quota_used',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('quota_used',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('app_triggers', schema=None) as batch_op:
        batch_op.alter_column('provider_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###
