"""add_pipeline_info_6

Revision ID: 224fba149d48
Revises: d466c551816f
Create Date: 2025-06-11 11:55:01.179201

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224fba149d48'
down_revision = 'd466c551816f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_built_in_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', models.types.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('updated_by', models.types.StringUUID(), nullable=True))

    with op.batch_alter_table('pipeline_customized_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', models.types.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('updated_by', models.types.StringUUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_customized_templates', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('pipeline_built_in_templates', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
