"""add created_by_account_id and created_by_role to api_tokens

Revision ID: e0e8c4b0a3c6
Revises: 669ffd70119c
Create Date: 2025-11-13 20:31:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e0e8c4b0a3c6'
down_revision = '669ffd70119c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist before adding them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('api_tokens')]

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        if 'created_by_account_id' not in existing_columns:
            # Add created_by_account_id with nullable=True first
            batch_op.add_column(sa.Column('created_by_account_id', sa.String(length=255), nullable=True))

        if 'created_by_role' not in existing_columns:
            # Add created_by_role with nullable=True first
            batch_op.add_column(sa.Column('created_by_role', sa.String(length=16), nullable=True))

    # Update existing records to have the owner's account_id and 'owner' role
    # This ensures backward compatibility - all existing tokens will work as owner tokens
    op.execute("""
        UPDATE api_tokens
        SET created_by_account_id = (
            SELECT ta.account_id
            FROM tenant_account_joins ta
            WHERE ta.tenant_id = api_tokens.tenant_id
                AND ta.role = 'owner'
            ORDER BY ta.created_at ASC
            LIMIT 1
        ),
        created_by_role = 'owner'
        WHERE created_by_account_id IS NULL
    """)

    # Now make the columns non-nullable
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        if 'created_by_account_id' not in existing_columns:
            batch_op.alter_column('created_by_account_id',
                                 existing_type=sa.String(length=255),
                                 nullable=False)
            # Create index for created_by_account_id
            batch_op.create_index('api_token_created_by_account_idx', ['created_by_account_id'], unique=False)

        if 'created_by_role' not in existing_columns:
            batch_op.alter_column('created_by_role',
                                 existing_type=sa.String(length=16),
                                 nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('api_token_created_by_account_idx')
        batch_op.drop_column('created_by_role')
        batch_op.drop_column('created_by_account_id')
    # ### end Alembic commands ###