"""add github_connections table

Revision ID: a1b2c3d4e5f6
Revises: 3334862ee907
Create Date: 2026-01-15 12:00:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "3334862ee907"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        op.create_table(
            "github_connections",
            sa.Column("id", models.types.StringUUID(), server_default=sa.text("uuidv7()"), nullable=False),
            sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
            sa.Column("user_id", models.types.StringUUID(), nullable=False),
            sa.Column("app_id", models.types.StringUUID(), nullable=True),
            sa.Column("repository_owner", sa.String(length=255), nullable=False, server_default=""),
            sa.Column("repository_name", sa.String(length=255), nullable=False, server_default=""),
            sa.Column("branch", sa.String(length=255), nullable=False, server_default="main"),
            sa.Column("access_token", models.types.LongText(), nullable=False, server_default=""),
            sa.Column("refresh_token", models.types.LongText(), nullable=True),
            sa.Column("token_expires_at", sa.DateTime(), nullable=True),
            sa.Column("webhook_id", sa.String(length=255), nullable=True),
            sa.Column("webhook_secret", models.types.LongText(), nullable=True),
            sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP(0)"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id", name="github_connection_pkey"),
        )
    else:
        op.create_table(
            "github_connections",
            sa.Column("id", models.types.StringUUID(), nullable=False),
            sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
            sa.Column("user_id", models.types.StringUUID(), nullable=False),
            sa.Column("app_id", models.types.StringUUID(), nullable=True),
            sa.Column("repository_owner", sa.String(length=255), nullable=False, server_default=""),
            sa.Column("repository_name", sa.String(length=255), nullable=False, server_default=""),
            sa.Column("branch", sa.String(length=255), nullable=False, server_default="main"),
            sa.Column("access_token", models.types.LongText(), nullable=False, server_default=""),
            sa.Column("refresh_token", models.types.LongText(), nullable=True),
            sa.Column("token_expires_at", sa.DateTime(), nullable=True),
            sa.Column("webhook_id", sa.String(length=255), nullable=True),
            sa.Column("webhook_secret", models.types.LongText(), nullable=True),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False),
            sa.PrimaryKeyConstraint("id", name="github_connection_pkey"),
        )

    with op.batch_alter_table("github_connections", schema=None) as batch_op:
        batch_op.create_index("github_connection_tenant_id_idx", ["tenant_id"], unique=False)
        batch_op.create_index("github_connection_app_id_idx", ["app_id"], unique=False)
        batch_op.create_index("github_connection_user_id_idx", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("github_connections", schema=None) as batch_op:
        batch_op.drop_index("github_connection_user_id_idx")
        batch_op.drop_index("github_connection_app_id_idx")
        batch_op.drop_index("github_connection_tenant_id_idx")

    op.drop_table("github_connections")
    # ### end Alembic commands ###

