"""'add_max_active_request'

Revision ID: 6b6356b36008
Revises: 7b45942e39bb
Create Date: 2024-07-01 02:36:16.134769

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '6b6356b36008'
down_revision = '7b45942e39bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_active_requests', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('max_active_requests')

    # ### end Alembic commands ###
