"""apparently we can't use enum of assign values, to removed all of them

Revision ID: 88e183a5aaf1
Revises: 8d0f913c0f57
Create Date: 2024-07-31 17:41:47.828199

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88e183a5aaf1'
down_revision = '8d0f913c0f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_plans', schema=None) as batch_op:
        batch_op.alter_column('plan_type',
               existing_type=postgresql.ENUM('SANDBOX', 'PROFESSIONAL', 'TEAM', 'CUSTOM', name='plantype'),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('document_processing_priority',
               existing_type=postgresql.ENUM('STANDARD', 'PRIORITY', name='processingpriority'),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('support',
               existing_type=postgresql.ENUM('COMMUNITY_FORUMS', 'EMAIL_SUPPORT', 'PRIORITY_EMAIL_CHAT', name='supporttype'),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('tenant_plans', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=postgresql.ENUM('monthly', 'yearly', name='planinterval'),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'monthly'::planinterval"))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               existing_nullable=False)

    with op.batch_alter_table('tenant_plans', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('monthly', 'yearly', name='planinterval'),
               existing_nullable=False,
               existing_server_default=sa.text("'monthly'::planinterval"))

    with op.batch_alter_table('base_plans', schema=None) as batch_op:
        batch_op.alter_column('support',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('COMMUNITY_FORUMS', 'EMAIL_SUPPORT', 'PRIORITY_EMAIL_CHAT', name='supporttype'),
               existing_nullable=False)
        batch_op.alter_column('document_processing_priority',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('STANDARD', 'PRIORITY', name='processingpriority'),
               existing_nullable=False)
        batch_op.alter_column('plan_type',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('SANDBOX', 'PROFESSIONAL', 'TEAM', 'CUSTOM', name='plantype'),
               existing_nullable=False)

    # ### end Alembic commands ###
