"""add workflow to site

Revision ID: a31f72360d4f
Revises: 7b45942e39bb
Create Date: 2024-06-20 05:28:22.081291

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'a31f72360d4f'
down_revision = '7b45942e39bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow', sa.String(length=255), nullable=True, server_default='show'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('workflow')

    # ### end Alembic commands ###
