#!/bin/bash
set -euo pipefail

tail -F /var/log/squid/access.log 2>/dev/null &
tail -F /var/log/squid/error.log 2>/dev/null &
tail -F /var/log/squid/store.log 2>/dev/null &
tail -F /var/log/squid/cache.log 2>/dev/null &

AGENT_FILE_TARGETS_CONF=/etc/squid/dify_agent_file_targets.conf

extract_url_host() {
    local url="$1"
    local authority
    local host

    case "$url" in
        http://* | https://*) ;;
        *)
            echo "[ENTRYPOINT] AGENT_SSRF_PROXY_FILE_URL must use http or https" >&2
            return 1
            ;;
    esac

    authority="${url#*://}"
    authority="${authority%%/*}"
    if [[ -z "$authority" || "$authority" == *"@"* ]]; then
        echo "[ENTRYPOINT] AGENT_SSRF_PROXY_FILE_URL must contain a host without credentials" >&2
        return 1
    fi

    if [[ "$authority" == \[* ]]; then
        host="${authority#\[}"
        host="${host%%\]*}"
    else
        host="${authority%%:*}"
    fi

    if [[ -z "$host" || "$host" == *[!A-Za-z0-9._:-]* ]]; then
        echo "[ENTRYPOINT] AGENT_SSRF_PROXY_FILE_URL contains an invalid host" >&2
        return 1
    fi

    printf '%s\n' "$host"
}

write_agent_file_targets() {
    local file_url="${AGENT_SSRF_PROXY_FILE_URL:-}"
    local host
    local acl_type=dstdomain

    {
        echo "# Generated by docker-agent-entrypoint.sh."
        echo "# Allows the configured Dify file endpoint before private-network denial."
    } > "$AGENT_FILE_TARGETS_CONF"

    if [[ -z "${file_url//[[:space:]]/}" ]]; then
        return
    fi

    host="$(extract_url_host "$file_url")"
    if [[ "$host" == *:* || "$host" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        acl_type=dst
    fi

    if [[ "$acl_type" == dstdomain ]]; then
        printf 'acl dify_agent_file_target dstdomain -n %s\n' "$host" >> "$AGENT_FILE_TARGETS_CONF"
    else
        printf 'acl dify_agent_file_target dst %s\n' "$host" >> "$AGENT_FILE_TARGETS_CONF"
    fi
    printf 'http_access allow dify_agent_file_target path_files\n' >> "$AGENT_FILE_TARGETS_CONF"

    # Squid cannot inspect paths inside an HTTPS CONNECT tunnel. The configured
    # file host is therefore treated as trusted for HTTPS connectivity.
    if [[ "$file_url" == https://* ]]; then
        printf 'http_access allow CONNECT dify_agent_file_target\n' >> "$AGENT_FILE_TARGETS_CONF"
    fi
}

expand_env() {
    awk '{
        while(match($0, /\${[A-Za-z_][A-Za-z_0-9]*}/)) {
            var = substr($0, RSTART+2, RLENGTH-3)
            val = ENVIRON[var]
            $0 = substr($0, 1, RSTART-1) val substr($0, RSTART+RLENGTH)
        }
        print
    }' "$1"
}

echo "[ENTRYPOINT] replacing environment variables in the templates"
write_agent_file_targets
expand_env /etc/squid/squid.conf.template > /etc/squid/squid.conf
expand_env /etc/squid/dify_common.conf.template > /etc/squid/dify_common.conf

/usr/sbin/squid -Nz
echo "[ENTRYPOINT] starting squid"
/usr/sbin/squid -f /etc/squid/squid.conf -NYC 1
