export const ACCOUNT_SETTING_TAB = {
  MEMBERS: 'members',
  ROLES_AND_PERMISSIONS: 'roles-and-permissions',
  PERMISSION_SET: 'permission-set',
  BILLING: 'billing',
  WORKFLOW_LOG_ARCHIVES: 'workflow-log-archives',
  CUSTOM: 'custom',
  PREFERENCES: 'preferences',
} as const

export type AccountSettingTab = (typeof ACCOUNT_SETTING_TAB)[keyof typeof ACCOUNT_SETTING_TAB]

export const ACCOUNT_SETTING_TAB_VALUES = [
  ACCOUNT_SETTING_TAB.MEMBERS,
  ACCOUNT_SETTING_TAB.ROLES_AND_PERMISSIONS,
  ACCOUNT_SETTING_TAB.PERMISSION_SET,
  ACCOUNT_SETTING_TAB.BILLING,
  ACCOUNT_SETTING_TAB.WORKFLOW_LOG_ARCHIVES,
  ACCOUNT_SETTING_TAB.CUSTOM,
  ACCOUNT_SETTING_TAB.PREFERENCES,
] as const
