project-includes = ["."]
project-excludes = [
    "tests/",
    ".venv",
    "migrations/",
    "core/rag",
    "extensions/storage/",
    "services/",
    "core/",
    "controllers/",
    "extensions/",
    "libs/",
    "models/",
    "factories/",
    "schedule/queue_monitor_task.py",
    "factories/variable_factory.py",
]
python-platform = "linux"
python-version = "3.11.0"
