name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy API Service
        run: |
          railway login --token $RAILWAY_TOKEN
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service api --detach

      - name: Deploy Web Service
        run: |
          railway up --service web --detach
          
      - name: Deploy Worker Service
        run: |
          railway up --service worker --detach

      - name: Wait for Deployment
        run: |
          echo "Waiting for services to start..."
          sleep 60

      - name: Run Database Migrations
        run: |
          railway run --service api "python -m flask db upgrade"

      - name: Deployment Status
        run: |
          echo "✅ Deployment completed!"
          echo "🌐 Your Dify instance should be available at:"
          railway status
