name: Build and Push Dify API and Web Docker Images (ARM64)

on:
  workflow_dispatch:

concurrency:
  group: build-push-${{ github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - service_name: "build-api-arm64"
            image_name: "registry.cn-hangzhou.aliyuncs.com/kindlingx/apo-dify-api"
            context: "api"
            platform: linux/arm64
          - service_name: "build-web-arm64"
            image_name: "registry.cn-hangzhou.aliyuncs.com/kindlingx/apo-dify-web"
            context: "web"
            platform: linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image metadata
        id: build-image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          DATE=$(date +"%Y%m%d%H%M%S%Z")
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's#[^a-zA-Z0-9._-]#-#g')
          IMAGE_TAG_NAME="${BRANCH_NAME}-${COMMIT_HASH::7}-${DATE}"
          echo "IMAGE_TAG_NAME=$IMAGE_TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "IMAGE_FULL_TAG=${{ matrix.image_name }}:${IMAGE_TAG_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.context }}"
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_FULL_TAG }}
          cache-from: type=gha,scope=${{ matrix.service_name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service_name }}
