name: Api Staging Deployment

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-staging]

jobs:
  call-deployment-in-local-repo:
    uses: ./.github/workflows/deploy.yml
    with:
      APPLICATION_NAME: dify-api
      DEPLOYMENT_ENV: staging
      ECR_REPOSITORY: ai-dify-api
      ECS_CLUSTER: ai-dify
      SECURITY_GROUP_IDS_SSM: /staging/security-groups
      SUBNET_IDS_SSM: /staging/subnet-ids
      VPC_ID_SSM: /staging/vpc-id
      SNS_TO_LARK_LAMBDA_ARN: /staging/lambda/sns-to-lark
      CERERTIFICATE_US_EAST_2_ARN: /staging/certificate
      ECS_EXECUTION_ROLE_ARN: /staging/ecs-execution-role
      APP_PORT: 5001
      MODE: api
      DOCKER_IMAGE_NAME: dify-api
      HEALTH_CHECK: /console/api/ping
      TEMPLATE: cloudformation-ecs-service-template.yml
      DOCKERFILEDIR: api



    secrets:
      DEPLOYMENT_AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY_ID_STAGING }}
      DEPLOYMENT_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYMENT_AWS_SECRET_ACCESS_KEY_STAGING }}
      ED25519_CI_KEY: ${{ secrets.ED25519_CI_KEY }}
      PAT: ${{ secrets.PAT }}
 
