concurrency: 10                           # Number of concurrent users
base: 'http://localhost:5001'            # Base URL for the API
iterations: 100                          # Total number of requests to make
rampup: 5                                # Seconds to gradually start all threads

plan:
  - name: 'Dify Workflow Execution'
    request:
      url: /v1/workflows/run
      method: POST
      body: |
        {
          "inputs": {
            "question": "What is the capital of France?"
          },
          "user": "benchmark-user",
          "response_mode": "blocking"
        }
      headers:
        Authorization: 'Bearer {{ api_token }}'
        Content-Type: 'application/json'